blank_issues_enabled: false
contact_links:
  - name: VPI Website
    url: https://virtualpilotinstitute.org/
    about: VPI Website
  - name: Discord
    url: https://virtualpilotinstitute.org/discord
    about: Feel free to join our Discord to discuss stuff, including possible bugs and suggestions!