name: Bug Report for VPI Desktop App
description: Create a report to help us improve the VPI Desktop App
labels: [ "bug", "pending" ]
assignees: [ "JackMcLeanGSY" ]
projects: [ "Pilot-Desktop-app" ]
body:
  - type: markdown
    attributes:
      value: |
        Hello! Thank you for reporting a bug in the VPI Desktop App.
        
        Before submitting your bug, please ensure that you have checked for existing bug reports to avoid duplicates. You can filter by the "bug" label to see if it has already been reported.

        Also, if you’ve encountered a problem with a specific feature or page within the app, please make sure to specify it below.
  - type: input
    id: discord_username
    attributes:
      label: Your Discord Username
      description: Your Discord username will help us contact you if we need more information.
    validations:
      required: true
  - type: textarea
    id: describe_bug
    attributes:
      label: Describe the Bug
      description: A clear and concise description of what the bug is in the VPI Desktop App.
    validations:
      required: true
  - type: textarea
    id: to_reproduce
    attributes:
      label: Steps to Reproduce
      description: Please provide the steps to reproduce the bug within the VPI Desktop App.
    validations:
      required: true
  - type: textarea
    id: expected_behavior
    attributes:
      label: Expected Behavior
      description: What did you expect to happen when using the app?
    validations:
      required: true
  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots (if applicable)
      description: If applicable, please attach any screenshots or logs that might help explain the bug.
    validations:
      required: false
  - type: input
    id: os_browser
    attributes:
      label: Desktop OS and Version
      description: Please provide your operating system and version (e.g., Windows 10, macOS 11).
    validations:
      required: true
  - type: input
    id: app_version
    attributes:
      label: VPI Desktop App Version
      description: What version of the VPI Desktop App are you using? (e.g., v1.0.0).
    validations:
      required: true
  - type: input
    id: device_os_browser
    attributes:
      label: Device and OS (if applicable)
      description: If you’re experiencing the bug on a mobile version, provide the device and OS details (e.g., iPhone 12, iOS 15).
    validations:
      required: false
  - type: textarea
    id: additional_info
    attributes:
      label: Additional Context
      description: Please provide any additional information that could be helpful in diagnosing the bug.
    validations:
      required: false
  - type: checkboxes
    id: validation
    attributes:
      label: Validation
      description: Please validate your report
      options:
        - label: I have searched for other reports and didn't find any alike
          required: true
        - label: I have tried restarting the app, and the issue persists
          required: true
        - label: The bug still occurs after updating to the latest version of the app
          required: true
